import { ClerkProvider } from '@/components/clerk-provider'
import { ThemeProvider } from '@/components/theme-provider'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/navbar'
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar'
import { SignedIn, SignedOut } from '@clerk/nextjs'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`h-full ${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
      >
        <body className="h-full">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {/* App shell for authenticated users */}
            <SignedIn>
              <SidebarProvider>
                <div className="min-h-screen flex flex-col">
                  <div className="flex flex-1 min-h-0 min-w-0">
                    <Navbar />
                   
                      <main className="flex flex-col w-full h-full flex-1 min-h-0 min-w-0 p-6 overflow-auto">
                        {children}
                      </main>
            
                  </div>
                </div>
              </SidebarProvider>
            </SignedIn>
            {/* Minimal layout for signed-out users */}
            <SignedOut>
              <div className="min-h-screen flex flex-col">
                <main className="flex-1">{children}</main>
              </div>
            </SignedOut>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
